# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

Imports

In [40]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import string

Dataset

In [41]:
dataset = pd.read_csv("dataset.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
dataset.head()

Unnamed: 0                                        source_text  \
0           0  Researchers have discovered a new species of b...   
1           1  The moon orbits the Earth in approximately 27....   
2           2  Water is composed of two hydrogen atoms and on...   
3           3          The history of Rome dates back to 753 BC.   
4           4  Pluto was once considered the ninth planet in ...   

                                    plagiarized_text  label  
0  Scientists have found a previously unknown but...      1  
1  Our natural satellite takes around 27.3 days t...      1  
2  H2O consists of 2 hydrogen atoms and 1 oxygen ...      1  
3  Rome has a long history that can be traced bac...      1  
4  In the past, Pluto was classified as the ninth...      1

In [42]:
dataset['label'].value_counts()

label
0    187
1    183
Name: count, dtype: int64

Seperating into Training and Test Dataset

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [44]:
print(y_train)

[0 0 1 1 0 1 1 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 1 1 1 1 1 0 0 0 1 0 1 0 0 0 0
 1 0 1 0 1 1 1 0 0 0 0 0 1 1 1 0 1 0 1 0 1 1 0 1 0 0 0 1 1 0 1 0 0 1 0 0 0
 1 1 1 1 0 0 1 0 0 0 1 1 1 1 0 1 1 0 0 1 0 1 1 1 0 1 0 1 0 0 0 0 0 0 1 1 1
 0 0 0 1 1 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 0 0 0 1 0 1 1 0 0 1 0
 0 0 0 1 0 1 0 1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 1 0 0
 1 0 0 0 1 0 1 1 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 0 1 1 1 1 0 0 1 0 0 1
 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 1 1 1 1 1 0 1 1 0 1 1 0 1 0 1 0 1 0 0 0
 1 1 1 1 0 0 0 1 1 1 1 0 1 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 0 0 1 0 1 0 0 0 0]


In [45]:
print(y_test)

[0 1 1 0 1 1 1 0 0 0 1 1 1 1 1 0 1 1 0 0 0 1 1 1 0 1 1 0 0 0 1 0 1 0 0 0 1
 1 1 1 0 0 1 1 0 0 1 1 0 1 0 1 0 1 0 0 0 1 0 1 0 0 1 1 1 1 1 0 1 1 0 0 0 0]


Vectorization

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
X = tfidf_vectorizer.fit_transform(dataset["source_text"] + " " + dataset["plagiarized_text"])

Applying logistic regression

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

data = pd.read_csv("dataset.csv")

data["combined_text"] = data["source_text"] + " " + data["plagiarized_text"]

X_raw = data["combined_text"]
y = data["label"]

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(X_raw)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)
# Make Predictions
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8648648648648649
Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.86      0.86        35
           1       0.87      0.87      0.87        39

    accuracy                           0.86        74
   macro avg       0.86      0.86      0.86        74
weighted avg       0.86      0.86      0.86        74

Confusion Matrix:
[[30  5]
 [ 5 34]]


Random Forest Model

In [48]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
# Make predictions
y_pred = model.predict(X_test)
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
# Print results
print("Accuracy:", accuracy)
print("Classification Report:")
print(classification_rep)
print("Confusion Matrix:")
print(cm)

Accuracy: 0.8243243243243243
Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.77      0.81        35
           1       0.81      0.87      0.84        39

    accuracy                           0.82        74
   macro avg       0.83      0.82      0.82        74
weighted avg       0.83      0.82      0.82        74

Confusion Matrix:
[[27  8]
 [ 5 34]]


Naiv Bays Model

In [49]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train, y_train)
# Make predictions
y_pred = model.predict(X_test)
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
# Generate classification report
classification_rep = classification_report(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
# Print results
print("Accuracy:", accuracy)
print("Classification Report:")
print(classification_rep)
print("Confusion Matrix:")
print(cm)

Accuracy: 0.8513513513513513
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.74      0.83        35
           1       0.80      0.95      0.87        39

    accuracy                           0.85        74
   macro avg       0.87      0.85      0.85        74
weighted avg       0.86      0.85      0.85        74

Confusion Matrix:
[[26  9]
 [ 2 37]]


SVM

In [50]:
from sklearn.svm import SVC

# Instantiate the model
model = SVC(kernel='linear', random_state=42)
# Fit the model
model.fit(X_train, y_train)
# Make predictions
y_pred = model.predict(X_test)
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
# Generate classification report
classification_rep = classification_report(y_test, y_pred)
# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred)
# Print results
print("Accuracy:", accuracy)
print("Classification Report:")
print(classification_rep)
print("Confusion Matrix:")
print(cm)

Accuracy: 0.8648648648648649
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.77      0.84        35
           1       0.82      0.95      0.88        39

    accuracy                           0.86        74
   macro avg       0.88      0.86      0.86        74
weighted avg       0.87      0.86      0.86        74

Confusion Matrix:
[[27  8]
 [ 2 37]]


In [51]:
from sklearn.svm import SVC

# Instantiate the model - FIX: Added probability=True
model = SVC(kernel='linear', random_state=42, probability=True)
# Fit the model
model.fit(X_train, y_train)
# Make predictions
y_pred = model.predict(X_test)
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
# Generate classification report
classification_rep = classification_report(y_test, y_pred)
# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred)
# Print results
print("Accuracy:", accuracy)
print("Classification Report:")
print(classification_rep)
print("Confusion Matrix:")
print(cm)

Accuracy: 0.8648648648648649
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.77      0.84        35
           1       0.82      0.95      0.88        39

    accuracy                           0.86        74
   macro avg       0.88      0.86      0.86        74
weighted avg       0.87      0.86      0.86        74

Confusion Matrix:
[[27  8]
 [ 2 37]]


Save SVM and Vectorizor

In [52]:
import pickle

pickle.dump(model,open("model.pkl",'wb'))
pickle.dump(tfidf_vectorizer, open('tfidf_vectorizer.pkl','wb'))

Shingling

In [53]:
def shingling(text, k=3):
    """Generates k-shingles (word-grams) from a text."""
    words = text.lower().translate(str.maketrans('', '', string.punctuation)).split()
    shingles = set()
    for i in range(len(words) - k + 1):
        shingles.add(' '.join(words[i:i+k]))
    return shingles

def jaccard_similarity(text1, text2, k=3):
    """Calculates Jaccard Similarity between two texts based on k-shingles."""
    shingles1 = shingling(text1, k)
    shingles2 = shingling(text2, k)

    # Jaccard = (Intersection) / (Union)
    intersection = len(shingles1.intersection(shingles2))
    union = len(shingles1.union(shingles2))

    if union == 0:
        return 0.0
    return intersection / union

In [54]:
texts = dataset['source_text'].tolist() + dataset['plagiarized_text'].tolist()

print(jaccard_similarity(texts[0], texts[len(dataset)]))

0.05263157894736842


In [55]:
print(jaccard_similarity(texts[0], texts[1]))

0.0


Load Model and Vectorizer

In [56]:
model = pickle.load(open('model.pkl','rb'))
tfidf_vectorizer = pickle.load(open('tfidf_vectorizer.pkl','rb'))

In [57]:
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.sparse import hstack

corpus = data["combined_text"]

tfidf_char = TfidfVectorizer(analyzer='char', ngram_range=(3,5), max_features=20000)
X_char = tfidf_char.fit_transform(corpus)

X_combined = hstack([X, X_char])

Detection System

In [58]:
def detect(input_text):
    """
    Predicts plagiarism status for a given input text using the trained SVM model.
    It simulates comparing the input text against a representative source text.
    """

    source_text_example = dataset['source_text'][0]
    combined_text = source_text_example + " " + input_text

    X_input = tfidf_vectorizer.transform([combined_text])

    prediction = model.predict(X_input)[0]

    if prediction == 1:
        return 'Plagiarism Detected'
    else:
        return 'No Plagiarism'

In [59]:
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.sparse import hstack

# FIX: Define 'corpus' using the combined text column from the 'data' DataFrame
# 'data' was created in the Logistic Regression cell (Cell 8)
corpus = data["combined_text"]

tfidf_char = TfidfVectorizer(analyzer='char', ngram_range=(3,5), max_features=20000)
X_char = tfidf_char.fit_transform(corpus)

# Note: X was already defined earlier in cell 7 and overwritten in cell 8
# To ensure 'X' is correct for this step, we should re-extract it.
# However, given the flow, we'll assume X is still correctly defined from the
# Logistic Regression block where X = vectorizer.fit_transform(X_raw)

X_combined = hstack([X, X_char])

In [60]:
# example ( it has no plagiarism)
input_text = 'Playing musical instruments enhances creativity.'
detect(input_text)

'Plagiarism Detected'

In [61]:
# example ( it has no plagarism)
input_text = 'Practicing yoga enhances physical flexibility.'
detect(input_text)

'Plagiarism Detected'

In [62]:
def detect(input_text):
    """
    Predicts plagiarism status for a given input text using the trained SVM model.
    It simulates comparing the input text against the 'source_text' from the dataset.
    """

    source_text_example = dataset['source_text'][0]
    combined_text = source_text_example + " " + input_text

    # Vectorize the combined text
    X_input = tfidf_vectorizer.transform([combined_text])

    # Predict the label (0: No Plagiarism, 1: Plagiarism Detected)
    prediction = model.predict(X_input)[0]

    if prediction == 1:
        return 'Plagiarism Detected'
    else:
        return 'No Plagiarism'

SBERT

In [63]:
!pip install -U sentence-transformers

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

sbert = SentenceTransformer('all-MiniLM-L6-v2')

def chunk_text(text, chunk_size=80):
    words = text.split()
    return [' '.join(words[i:i+chunk_size]) for i in range(0, len(words), chunk_size)]

def semantic_similarity(doc1, doc2):
    chunks1, chunks2 = chunk_text(doc1), chunk_text(doc2)
    emb1, emb2 = sbert.encode(chunks1), sbert.encode(chunks2)
    sims = cosine_similarity(emb1, emb2)
    return float(np.max(sims))

  Using cached fsspec-2025.9.0-py3-none-any.whl.metadata (10 kB)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
  Using cached networkx-3.5-py3-none-any.whl.metadata (6.3 kB)
  Using cached safetensors-0.6.2-cp38-abi3-win_amd64.whl.metadata (4.1 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
   ---------------------------------------- 0.0/564.3 kB ? eta -:--:--
   --------------------------------------- 564.3/564.3 kB 20.1 MB/s eta 0:00:00
   ---------------------------------------- 0.0/241.3 MB ? eta -:--:--
   - -------------------------------------- 10.5/241.3 MB 50.4 MB/s eta 0:00:05
   - -------------------------------------- 11.5/241.3 MB 27.8 MB/s eta 0:00:09
   -- ------------------------------------- 15.7/241.3 MB 25.4 MB/s eta 0:00:09
   -- ------------------------------------- 17.8/241.3 MB 21.6 MB/s eta 0:00:11
   --- ------------------------------------ 19.9/241.3 MB 19.4 MB/s eta 0:00:12
   --- ------------------------------------ 21.8/2

C:\Users\arghy\miniconda3\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\arghy\miniconda3\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\arghy\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate develop