# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

Imports

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import string

Dataset

In [9]:
dataset = pd.read_csv("dataset.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
dataset.head()

Unnamed: 0                                        source_text  \
0           0  Researchers have discovered a new species of b...   
1           1  The moon orbits the Earth in approximately 27....   
2           2  Water is composed of two hydrogen atoms and on...   
3           3          The history of Rome dates back to 753 BC.   
4           4  Pluto was once considered the ninth planet in ...   

                                    plagiarized_text  label  
0  Scientists have found a previously unknown but...      1  
1  Our natural satellite takes around 27.3 days t...      1  
2  H2O consists of 2 hydrogen atoms and 1 oxygen ...      1  
3  Rome has a long history that can be traced bac...      1  
4  In the past, Pluto was classified as the ninth...      1

In [10]:
dataset['label'].value_counts()

label
0    187
1    183
Name: count, dtype: int64

Seperating into Training and Test Dataset

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
print(y_train)

345    0
192    0
75     1
84     1
358    0
      ..
71     1
106    0
270    0
348    0
102    0
Name: label, Length: 296, dtype: int64


In [13]:
print(y_test)

[0 1 1 0 1 1 1 0 0 0 1 1 1 1 1 0 1 1 0 0 0 1 1 1 0 1 1 0 0 0 1 0 1 0 0 0 1
 1 1 1 0 0 1 1 0 0 1 1 0 1 0 1 0 1 0 0 0 1 0 1 0 0 1 1 1 1 1 0 1 1 0 0 0 0]


Vectorization

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
X = tfidf_vectorizer.fit_transform(dataset["source_text"] + " " + dataset["plagiarized_text"])

Applying logistic regression

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# STEP 1: Load your data (replace this with your actual data source)
# Make sure 'source_text', 'plagiarized_text', and 'label' exist
data = pd.read_csv("dataset.csv")  # <- Replace with your actual file

# STEP 2: Combine the two text columns
data["combined_text"] = data["source_text"] + " " + data["plagiarized_text"]

# STEP 3: Extract features and labels
X_raw = data["combined_text"]
y = data["label"]  # Replace with your actual label column name

# STEP 4: Vectorize the text
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(X_raw)

# STEP 5: Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# STEP 6: Train the model
model = LogisticRegression()
model.fit(X_train, y_train)

# STEP 7: Predict and evaluate
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8648648648648649
Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.86      0.86        35
           1       0.87      0.87      0.87        39

    accuracy                           0.86        74
   macro avg       0.86      0.86      0.86        74
weighted avg       0.86      0.86      0.86        74

Confusion Matrix:
[[30  5]
 [ 5 34]]


Random Forest Model

In [16]:
from sklearn.ensemble import RandomForestClassifier
# Instantiate the model
model = RandomForestClassifier(n_estimators=100, random_state=42)
# Fit the model
model.fit(X_train, y_train)
# Make predictions
y_pred = model.predict(X_test)
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
# Generate classification report
classification_rep = classification_report(y_test, y_pred)
# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred)
# Print results
print("Accuracy:", accuracy)
print("Classification Report:")
print(classification_rep)
print("Confusion Matrix:")
print(cm)

Accuracy: 0.8243243243243243
Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.77      0.81        35
           1       0.81      0.87      0.84        39

    accuracy                           0.82        74
   macro avg       0.83      0.82      0.82        74
weighted avg       0.83      0.82      0.82        74

Confusion Matrix:
[[27  8]
 [ 5 34]]


Naiv Bays Model

In [17]:
from sklearn.naive_bayes import MultinomialNB
# Instantiate the model
model = MultinomialNB()
# Fit the model
model.fit(X_train, y_train)
# Make predictions
y_pred = model.predict(X_test)
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
# Generate classification report
classification_rep = classification_report(y_test, y_pred)
# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred)
# Print results
print("Accuracy:", accuracy)
print("Classification Report:")
print(classification_rep)
print("Confusion Matrix:")
print(cm)

Accuracy: 0.8513513513513513
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.74      0.83        35
           1       0.80      0.95      0.87        39

    accuracy                           0.85        74
   macro avg       0.87      0.85      0.85        74
weighted avg       0.86      0.85      0.85        74

Confusion Matrix:
[[26  9]
 [ 2 37]]
